### ISSUE TITLE
Hello again!

### ISSUE THREAD

**Issue by lylax47** [czcorpus/kontext#1389]
Hi again!

My hard drive recently crashed, and I am trying to reinstall per the instructions that I wrote, but for some reason when I try to access localhost/kontext on the browser it returns a 404 error. The path is correct and the files are there. I thought this might be an error with permissions, so I changed file owner to www-data, but apache still can not find the file. Below is my kontext.conf file. I've already rewrote the config.xml file and compiled everything without and errors. Any ideas on what may be causing the issue?

<VirtualHost *:80>
    ServerName my.domain
    DocumentRoot /var/www/kontext/public

    Alias /files /var/www/kontext/public/files
    <Directory /var/www/kontext/public/files>
        Order deny,allow
        Allow from all
    </Directory>

    WSGIScriptAlias /kontext /var/www/kontext/public/app.py
    WSGIDaemonProcess kontext_app processes=2 threads=15 display-name=%{GROUP}
    WSGIProcessGroup %{GLOBAL}
</VirtualHost>

Also the Russian documentation was ready a while ago. I got distracted in the summer and forgot to send it to you. My apologies. However, seeing as the install instructions I wrote don't currently work, it seems I still need to edit them after this install.

**Comment by tomachalek** [comment]
The config you have pasted uses [VirtualHost](https://httpd.apache.org/docs/2.4/vhosts/name-based.html) and requires you to have the *my.domain* name defined in your network or in your case at your localhost. I.e. the system must know what IP address (127.0.0.1 in your case as you use your local machine as a server) *my.domain* maps to. The solution depends on an operating system:

### Windows

Edit */windows/system32/drivers/etc/hosts* by adding the line

```
127.0.0.1    my.domain
````

### Linux

edit */etc/hosts* by adding the line

```
127.0.0.1    my.domain
````

If you want to access KonText via a URL like *http://localhost/kontext* then you have to use [Location](http://httpd.apache.org/docs/current/mod/core.html#location) directive which allows you to define a virtual directory structure on your local Apache webserver (http://localhost/kontext, http://localhost/other_application,...).

In my opinion, the easier way is to define some fake hostname like *kontext.test* in hour *hosts* file (see above) and define a virtualhost (*ServerName kontext.test* in this case).

**Comment by lylax47** [comment]
Thank you! I got rid of the 404 error. When I test it, it gets stuck trying to get a t/f value from "use_conc_toolbar". I can't find anything in the conf.xml connected with this aside from possibly the language toolbar, under <getlang>, which I have omitted for the time being. I've posted the tail of the error below:
```
[Thu Nov 03 12:31:33.821319 2016] [wsgi:error] [pid 10241:tid 140092496668416] [client 127.0.0.1:53922]     super(Actions, self)._add_globals(result, methodname, action_metadata)
[Thu Nov 03 12:31:33.821354 2016] [wsgi:error] [pid 10241:tid 140092496668416] [client 127.0.0.1:53922]   File "/var/www/kontext/public/../lib/kontext.py", line 1083, in _add_globals
[Thu Nov 03 12:31:33.822064 2016] [wsgi:error] [pid 10241:tid 140092496668416] [client 127.0.0.1:53922]     result['use_conc_toolbar'] = settings.get_bool('global', 'use_conc_toolbar')
[Thu Nov 03 12:31:33.822100 2016] [wsgi:error] [pid 10241:tid 140092496668416] [client 127.0.0.1:53922]   File "/var/www/kontext/public/../lib/settings.py", line 109, in get_bool
[Thu Nov 03 12:31:33.822296 2016] [wsgi:error] [pid 10241:tid 140092496668416] [client 127.0.0.1:53922]     }[fixed_key]
[Thu Nov 03 12:31:33.822344 2016] [wsgi:error] [pid 10241:tid 140092496668416] [client 127.0.0.1:53922] KeyError: 'none'
```

**Comment by tomachalek** [comment]
You're welcome.

KonText 0.9 and up contains a new configuration directive *use_conc_toolbar* in the section *global*. If set to *1* (or *true*) then KonText displays a view options shortcut. There is also an additional information regarding displaying of positional attributes available there - whether they are displayed directly in the text or on *mouseover*) directly in the concordance view box - which is a new function in KonText 0.9. In the future, this new "toolbar" will likely contain some more items.

**Comment by lylax47** [comment]
Thanks again! It's working now. By the way, in the current build that I cloned the tag use_conc_toolbar was missing from the conf.sample.xml.

**Comment by tomachalek** [comment]
I see, thanks for the remark. I am going to fix that.

**Comment by lylax47** [comment]
Last thing: Where in the config.xml file do you specify the path to the corpora vert files? Is this a set location? If so, where?

**Comment by tomachalek** [comment]
KonText's config.xml requires only a path to a directory where so called [registry](https://www.sketchengine.co.uk/corpus-configuration-file-all-features/) (aka corpus configuration file) files are located. Each registry file is named after its related corpus. I.e. if you want a corpus named "test2016" then there should be a registry file "test2016" in the directory specified in */corpora/manatee_registry* directive. 

Registry files are used by *Manatee* indexing/search engine to be able to know what is the structure of a corpus and where are its indexed data. Vertical files you mentioned are not involved here directly. You have to "compile" (index) them into a binary form understood by Manatee. This is done by a command-line utility *compilecorp* distributed with Manatee-open engine. But first, you have to have a respective registry file ready as *compilecorp* requires it too.

Here is how a registry file for the *susanne* corpus (which can be freely downloaded from [manatee-open project page](https://nlp.fi.muni.cz/trac/noske/wiki/Downloads)) looks like:

```
NAME "susanne"
PATH "/var/local/corpora/indexed/susanne"
VERTICAL "/var/lib/manatee/vert/susanne.vert"
ENCODING utf-8
INFO "Susanne corpus"

ATTRIBUTE word
ATTRIBUTE lemma
ATTRIBUTE tag
ATTRIBUTE status


STRUCTURE doc {
	ATTRIBUTE file
	ATTRIBUTE n
}

STRUCTURE p
STRUCTURE head {
	ATTRIBUTE type
}

STRUCTURE font {
	ATTRIBUTE type
}

STRUCTURE g
```

**Comment by lylax47** [comment]
Thanks so much again! That wasn't the issue actually, but I got it figured out.

**Comment by lylax47** [comment]
I'm curious, aside from designating a redis db, what else is required to use the user creation, login/logout functions of Kontext? Right now I can get to the login page, but I'm not able to create any new users.

**Comment by tomachalek** [comment]
There are two records a user must have within Redis to be able to log-in to KonText and use some corpora. Unfortunately, there is no GUI-based way how to do this. You have to add the entries manually.

## key user:[id]

Value is a JSON serialized object. Example for **user:1**:

```json
{
  "id": 1,
  "username": "john", 
  "pwd_hash": "..........md5...of.a.password...", 
  "firstname": "John", 
  "lastname": "Doe"
}
```

The password store method is not quite on par with today's standards but it can be easily updated to use a better hash algorithm along with some password salting. 

## key corplist:user:[id]

Value is a JSON serialized array. Example for **corplist:user:1**:

```json
["susanne", "bnc", "another_corpus"]
```

Adding/removing keys in Redis is easy (see [list of commands](http://redis.io/commands)), Just open *redis-cli* client and enter keys you need (just don't forget to escape JSON strings - quotes must have a backslash prefix).

Partial example (we assume that KonText is using Redis database number 1 (see "select 1", it is also configured in *config.xml's* *plugins/db* ) ):

```
bash$ redis-cli

select 1

set "user:1" "{\"id\": 1,.........
```

**Comment by lylax47** [comment]
So I created both keys on my db, but logging in on the "kontext.test/user/login" page doesn't work. For the password I just used a md5 hash generator, is this sufficient? Also when trying to access the login page through the link on "kontext.test/first_form" the server returns a 404. Any ideas why this might be?

**Comment by lylax47** [comment]
I fixed the 404 error, but I still can't get the user login to work. For reference I set the values as such:
```
set "user:1" "{\"id\": 1, \"username\": \"hsestudent\", \"pwd_hash\":     \"5f4dcc3b5aa765d61d8327deb882cf99\", \"firstname\": \"hse\", \"lastname\": \"student\"}"
```

I also separately updated the key for the corplist:
```
set "corplist:user:1" "[\"susanne\"]" 
```

**Comment by tomachalek** [comment]
Sorry, I have forgotten a thing. There must be also a mapping from usernames to user keys (i.e. "hsestudent" => "user:1"). This can be done as follows:

```
hset "user_index" "hsestudent" "user:1"
```
(It is actually another key-value table attached to a single key *user_index*.)

**Comment by lylax47** [comment]
That worked. Thanks! I've now tested all of the functions, and so far everything works except for frequency and collocations. Should these functions work, or are they currently not available?

**Comment by tomachalek** [comment]
Freqs and collocations should work too. Try to check KonText and webserver logs. It also depends on whether you use *celery* or *multiprocessing* calculation backend (see *global/calc_backend* in your *config.xml*). While the former should work if configured properly (all the related filesystem paths and permissions must be ok and Celery as a service must be configured and running too) the latter (multiprocessing) may have some issues as we do not use it in production and currently I do not have enough time to test in properly. Yet I am still ready to fix bugs reported.

**Comment by lylax47** [comment]
Yeah the problem is with celery. The sample celery config files are what the kontext is currently using. Is that ok? I fixed a few permissions errors and it seemed to be working, but now when I try to use frequency or collocations, kontext seems to get stuck in a loop, and is constantly loading, as such no errors are produced in the log, so I'm not really sure where to look next.

**Comment by lylax47** [comment]
What are the exact specifications for the config file elements listed below:

```
       <periodic_tasks conf="/var/www/kontext/conf/beatconfig.py">celery</periodic_tasks>
       <calc_backend conf="/var/www/kontext/conf/celeryconfig.py">celery</calc_backend>
       <conc_calc_backend conf="var/www/kontext/conf/celeryconfig.py">celery</conc_calc_backend>
```
When I try to run worker.py, I get the following error (I think that the problem is with the afore listed elements) :
```
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 276, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 478, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 500, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 348, in find_app
    sym = imp(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named py

```

**Comment by tomachalek** [comment]
Hello,

1) *conc_calc_backend* - this has been replaced by *calc_backend* in KonText 0.9.x. 

2) *calc_backend* and its *celeryconfig.py* - example:

```
BROKER_URL = 'redis://127.0.0.1:6379/12'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/12'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'Europe/Prague'
```

Where *BROKER_URL*, *CELERY_RESULT_BACKEND* can point to the same Redis instance as KonText does but you should select a different database ID (see the *12* in the example). *Json* values should remain as they are and time zone is self-explanatory (see [a list of valid timezones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)).

3) *beatconfig.py*

Unless you run also a Celery Beat instance (which is a periodic task runner based on Celery backend) which is not necessary in a development environment as it is used to clean caches, archive miscellaneous records etc. you can ignore this setting. However, here is an example of our config:

```
from celery.schedules import crontab

BROKER_URL = 'redis://127.0.0.1:6379/12'
CELERY_TASK_SERIALIZER = 'json'

CELERYBEAT_SCHEDULE = {
    'archive-old-concordances': {
        'task': 'conc_persistence.archive_concordance',
        'schedule': crontab(hour='*/6'),
        'kwargs': dict(cron_interval=30, key_prefix=None, dry_run=False)
    },
    'conc-cache-cleanup': {
        'task': 'conc_cache.conc_cache_cleanup',
        'schedule': crontab(hour='*/3', minute=0),
        'kwargs': dict(ttl=120, subdir=None, dry_run=False)
    },
    'conc-cache-cleanup-omezeni': {
        'task': 'conc_cache.conc_cache_cleanup',
        'schedule': crontab(hour='*/2', minute=0),
        'kwargs': dict(ttl=120, subdir='omezeni', dry_run=False)
    },
    'conc-cache-cleanup-aranea': {
        'task': 'conc_cache.conc_cache_cleanup',
        'schedule': crontab(hour='*/3', minute=10),
        'kwargs': dict(ttl=120, subdir='aranea', dry_run=False)
    },
    'clean-freqs-cache': {
        'task': 'worker.clean_freqs_cache',
        'schedule': crontab(hour='3', minute=20),
        'kwargs': {}
    },
    'clean-colls-cache': {
        'task': 'worker.clean_colls_cache',
        'schedule': crontab(hour='3', minute=20),
        'kwargs': {}
    }
}
```

**Comment by lylax47** [comment]
Awesome! Everything is up and running, and all the features are working, but the list of prior queries, but I think that's an issue with the config file, that I can solve on my own. Thank you so much for your help again! I'll definitely let you know when we get kontext finally up and running on the RNC server.

**Comment by tomachalek** [comment]
I am happy to hear that - especially considering the fact that the process of setting KonText up is not easy at all. But all the dependencies and services are there for a reason as we have to be able to handle quite a lot of queries (some of them long running). And the current set-up seems to be doing well (not perfectly but good enough). 

In case of a public KonText installation (or any installation with possibly more than just few requests) it is a good idea to set-up also the Celery Beat service along with some essential tasks - *conc_cache.conc_cache_cleanup*, *worker.clean_freqs_cache*, *worker.clean_colls_cache* (see the config above). This prevents disk drives and Redis from being filled by too many (mostly temporary) data. 

Looking forward to hear about KonText running on the RNC server!

**Comment by lylax47** [comment]
Can more than one person be logged in under a single user name at the same time? If this is the case, would there be some way to localize sub corpora creation/deletion, and user history, even while operating under the same user?

**Comment by tomachalek** [comment]
Unfortunately, this is not possible. There is always one-to-one mapping between a user account and query history and subcorpora.

**Comment by lylax47** [comment]
I'm curious, how do I need to format the kontext config.xml file and the registry, vert, and configured corpus files in order to have the option of using more that one corpus. I created the folder kontext/corpora/corplist, under which I placed the registry, and corpora files as such registry/    susanne/    RNCmain/    . In the corpora folders I placed the configured corpora files and a vert folder where the vert files are stored. I also edited the config file, so it would find the the registry files at this location. It still doesn't recognize that there are two corpora. Also when I just put RNCmain as the default corpora in the config file, kontext wont recognize it, but when I rename the registry and vert files susanne, it works fine. Any ideas?

**Comment by lylax47** [comment]
Also if I wanted to change the url for the login button, how would I do that? I'm familiar with django and flask, but I haven't ever used cheetah before, and I'm not sure where to find the given url path to edit. I want to make it so that the link goes to 'localhost/kontext.test/user/login' instead of 'localhost/user/login'

**Comment by tomachalek** [comment]
Hello, 
regarding the multiple corpora access you mentioned it looks like a problem with authorization via *default_auth* module (I suppose you are using the default authorization module). Please make sure you have proper *corplist:user:[user\_id]* records in Redis and also check that KonText (the *default\_auth* module to be more precise) actually reads them. It can be checked e.g. this way:

```python
# edit file lib/plugins/default_auth.py 
...
def permitted_corpora(self, user_id):
    corpora = self.db.get(self._mk_list_key(user_id), [])
    # now add the following:
    import logging
    logging.getLogger(__name__).info('Current user ID: %s' % (user_id,))
    logging.getLogger(__name__).info('Data access key: %s' % (self._mk_list_key(user_id),))
    logging.getLogger(__name__).info('User permitted corpora: %s' % (corpora,))
    # --- end of modification
    if IMPLICIT_CORPUS not in corpora:
        corpora.append(IMPLICIT_CORPUS)
    return dict([(self.canonical_corpname(c), c) for c in corpora])
```

Then try some KonText actions and check your application log (a file specified by *logging/path*). You should see a list of corpora you can actually access as a specific user. In case there is only the "susanne" corpus (which is defined in *IMPLICIT_CORPUS* variable) you should check a *user ID* and a database key used to access the record (see *self.\_mk\_list\_key(user_id)*.

**Comment by tomachalek** [comment]
Regarding the "login" button's URL, there are actually three URLs involved:

1. a URL of the login-form 
    * is is specified in *plugins/auth/login\_url*
    * in your case you should set something like *http://localhost/kontext.test/user/login*
2. a URL of the login action itself (i.e. the action which actually submits user credentials)
     * it is specified in *templates/user/login.tmpl* or on a page defined in (1) (there is an HTML *form* there containing an attribute *action* you can modify if you want)
3. a URL of the logout action (i.e. the actual logout action)
    * is is specified in *plugins/auth/logout\_url*
    * in your case you should set *http://localhost/kontext.test/user/logout*

**Comment by lylax47** [comment]
Ok I added the corpus 'RNCmain' into the corpus list for our user, but it still doesn't seem to recognize more than one corpora, when I go to the available corpora page. It just returns an error:

````
2016-12-19 19:12:54,518 [controller] ERROR: Traceback (most recent call last):
  File "/var/www/kontext/public/../lib/controller.py", line 888, in process_method
    method_ans = method(self._request)
  File "/var/www/kontext/public/../lib/actions/corpora.py", line 41, in corplist
    filter_dict=request.args)
  File "/var/www/kontext/public/../lib/plugins/abstract/corpora.py", line 223, in search
    filter_dict=filter_dict)
  File "/var/www/kontext/public/../lib/plugins/default_corparch/__init__.py", line 295, in search
    limit = int(self._corparch.max_page_size)
TypeError: int() argument must be a string or a number, not 'NoneType'

2016-12-19 19:12:54,519 [controller] ERROR: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/var/www/kontext/public/../lib/controller.py", line 783, in run
    methodname, tmpl, result = self.process_method(path[0], path, named_args)
  File "/var/www/kontext/public/../lib/controller.py", line 893, in process_method
    return self.process_error(ex, methodname, pos_args, named_args)
  File "/var/www/kontext/public/../lib/controller.py", line 851, in process_error
    raise e2
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by lylax47** [comment]
So I just decided to set the variable limit in kontext/lib/plugins/default_corp/__init__.py an arbitrarily high number. This worked, but corplist only lists susanne and not RNCmain, both of which it can see normally by default. However independent of the default corpus, it can only find susanne. Also I'm assuming the problem with the max_page_size is that it somehow needs to be initialized in the config file under corparch, but I have tried this with no luck. Below are a screenshot of the working corplist, as well as my config file.

![image](https://cloud.githubusercontent.com/assets/15244289/21511468/b5496dc4-ccba-11e6-8a80-d2a098e92dbe.png)

```
        <corparch>
            <module>default_corparch</module>
            <js_module>defaultCorparch</js_module>
            <file>/var/www/kontext/conf/config.xml</file>
            <root_elm_path>corpora/corplist</root_elm_path>
            <tag_prefix extension-by="default">+</tag_prefix>
            <max_num_hints extension-by="default">10</max_num_hints>
            <max_page_size>100</max_page_size>
        </corparch>
```

**Comment by lylax47** [comment]
Ok a few potential issues to report as well. First is connected with the login and logout urls. I wanted kontext to run under localhost with the wsgi alias kontext. Even when I change the url addresses in the configuration file it continuously searches for them at "localhost/user/login", and returns a 404 error. The only time that login and logout function, using the link, are when wsgi alias is not specified. Also regardless of url specified in the config file, if manually entered "http://localhost/kontext/user/login" will always work. I am not sure if this has to do with my own configuration or with the program. Let me know if you need any more information to help with this.

The next issue appears to be with running kontext on chrome. Do you know of any compatibility issues with this?

**Comment by tomachalek** [comment]
Regarding the posted config snippet, try to replace 

```xml
<max_page_size>...</max_page_size>
```

with 

```xml
<default_page_list_size extension-by="default">...</default_page_list_size>
```

**Comment by lylax47** [comment]
That solved the problem with hardcoding the size, but I still can't figure out why susanne is the only corpora that appears. The other corpus is in the database, as evinced by my ability to use it as the default corpus, but it does not appear under available corpora. This is my setup for corparch. Is this correct assuming that the RNCmain is the corpus name in the registry file? Is there anything else I should check?
```
        <corplist title="">
                <corplist title="susanne">
                        <corpus ident="susanne" sentence_struct="s"/>
                </corplist>
                <corplist title="RNCmain">
                        <corpus ident="RNCmain" web="http://hsecompling.wikispaces.com/visual" sentence_struct="s" tagset="http://nl.ijs.si/ME/V4/msd/html/msd-ru.html"/>
                </corplist>
                <corplist title='test'>
                        <corpus ident="test" sentence_struct="s"/>
                </corplist>
        </corplist>
```

**Comment by tomachalek** [comment]
The XML should look like this (in case you use *default_corparch*):

```xml
<corplist title="">
    <corpus ident="susanne" sentence_struct="s"/>
    <corpus ident="RNCmain" web="http://hsecompling.wikispaces.com/visual" sentence_struct="s" tagset="http://nl.ijs.si/ME/V4/msd/html/msd-ru.html"/>
     <corpus ident="test" sentence_struct="s"/>
 </corplist>
```

**Comment by lylax47** [comment]
Even after changing it, it still only seems to recognize susanne.

**Comment by tomachalek** [comment]
Have you tried to log what the *permitted_corpora()* method returns? (see my older comment https://github.com/czcorpus/kontext/issues/1389#issuecomment-267990864)

**Comment by lylax47** [comment]
Yes, it says that RNCmain is listed in permitted corpora. 
```
2017-01-25 11:47:14,328 [plugins.default_auth] INFO: User permitted corpora: [u'susanne', u'RNCmain']
```

**Comment by lylax47** [comment]
I can use the RNCmain corpus if I set it as default. It just doesn't seem to show up under available corpora.

**Comment by tomachalek** [comment]
Just for me to understand this properly. In case you have *susanne* as a default corpus - can you use *RNCmain* at least by manually entering an address: *http://your_address/first_form?corpname=RNCmain* ? 

In case we are talking only about not being able to see the corpus in the "available corpora* list, you can try to update the configuration entry in the following way:

```xml
<corplist title="">
    <corpus ident="susanne" sentence_struct="s"/>
    <corpus ident="RNCmain" web="http://hsecompling.wikispaces.com/visual" sentence_struct="s" tagset="http://nl.ijs.si/ME/V4/msd/html/msd-ru.html">
        <metadata>
            <featured />
       </metadata>
    </corpus>
     <corpus ident="test" sentence_struct="s"/>
 </corplist>
```

This should pin the corpus to the "featured" box which is available when you click the button containing a current corpus name on the query page (*first_form* action).

**Comment by lylax47** [comment]
Yes, when manually entering the address, it transfers to the RNC corpora. However I followed your next set of instructions and when I click on the current corpus on the first page nothing shows up.

**Comment by tomachalek** [comment]
It should look like this:

![kontext-corp-sel](https://cloud.githubusercontent.com/assets/439098/22287197/1cb71a86-e2f2-11e6-9da8-471bf57c2470.jpg)

Please try to open your browser's developer toolbar (typically: CTRL+SHIFT+I), reload the query page, click the button and see whether there are any errors reported in the console.

**Comment by lylax47** [comment]
The only errors that show up are related to kontext not being able to find certain image files.
![image](https://cloud.githubusercontent.com/assets/15244289/22291780/873c4960-e321-11e6-817a-d488693f3f2a.png)

**Comment by lylax47** [comment]
I thought it may be easier if you could just look at my configuration file.
[config.xml.zip](https://github.com/czcorpus/kontext/files/729756/config.xml.zip)

**Comment by lylax47** [comment]
Although that's probably a connected issue. Assuming it can't find these images, it probably can't find the js files for corparch as well, but that wouldn't explain then why only susanne is visible. The static files are stored under /var/www/kontext/pubic/kontex_files/.

**Comment by tomachalek** [comment]
Looking at your *config.xml* and the pasted screenshot I can see that you require static files to be served via */files_kontext* but KonText produces */files* paths. Few days ago, a user reported an error in KonText regarding static files paths. It should be fixed now i both *0.9.x* and *master* (= devel) branches. Please try to update your KonText and inspect what links are generated.

**Comment by lylax47** [comment]
I updated to 9.2 and am still getting all of the same errors: the same static files as above are not loading, the rnc corpus is not loading, and the url's for login and logout are static and do not change when modified in the config file. 

1. As far as the static files not being found. I have changed nothing since updating to 0.9.2. It appears that every other static file can load except for those. They are in the correct path and folder. Do you by chance need to specify them in the config file under theme?

2. The rnc corpus still will not show up properly under available copora. The only available corpus appearing is susanne. However when specified in the url "corname?=RNCmain", I can access it. I have made corplist.xml a separate file instead of included in the config.xml, but still nothing has changed. I would like to look at one of your working configurations with multiple corpora if possible to access the differences in our configuration files. It wouldn't somehow be affected by the registry file, or the corpus itself?

3.) Is context able to function normally if I specify the WSGIalias in the apache config file? I've tried deploying, whilst using /kontext as the alias, but the as a result the login and logout pages no longer function. The auth/login_url auth/logout_url configuration seems to have no affect on the actual url paths. I, for example, changed it as suggested previously to "http://localhost/kontext/user/login" and "http://localhost/kontext/user/logout" , and still had to use "localhost/user/login" manually to access these pages instead of using the button in the top right.  

I'm trying to solve this on my own as well, but if you have any ideas, or need any more information from me, let me know! Also could you by chance send me a working ready config file that you use, instead of the sample it comes with, so that I can compare mine to yours, that would be extremely helpful! Like I said, let me know if you need any more information. I tried to be as thorough explaining as possible.

**Comment by tomachalek** [comment]
Please try version 0.9.3 which is now available. The files path fix was added after the 0.9.2 release.

My local devel. config is here:

[kontext-conf.zip](https://github.com/czcorpus/kontext/files/755114/kontext-conf.zip)

**Comment by tomachalek** [comment]
I will try to look at the login/logout URL issue tomorrow or the day after it.

**Comment by lylax47** [comment]
Thank you very much! I resolved the issue with the static files, but 2 and 3 in the previous comment still seem to be issues. It may be worth noting that I tried to switch to using treeCorparch instead of using the defaultCorparch, and under this setting the RNCmain corpus appears. However unlike the default corpus, one is unable to access the corpora through the links provided on the GUI. In short, there seems to be a bug under the defaultCorparch where the corpora are not shown, and a bug under the treeCorparch where an error is thrown if one tries to access the corpora through the provided links.

**Comment by lylax47** [comment]
Dobré Ráno! I was wondering if you had found anything out about either the login/logout URL's or the corparchs?

**Comment by tomachalek** [comment]
Hello @lylax47 , 
sorry for such a late response but currently I am finishing the 0.10.x release which consumes most of my time. The login/logout problem should by solved by now - just update to the latest available commit in 0.9.x (see commit 32eecd6727). As regards the *corparch* plug-ins:
  * I am going to examine the *tree\_corparch* right now,
  * the *default\_plugin* will be probably more challenging but I will  try to devote some time to look at it

**Comment by tomachalek** [comment]
*tree_corparch* - everything seems to be working to me. I have even installed my devel KonText instance under a URL directory (something like your case: "http://localhost/kontext/") to make sure that the subdirectory ("kontext/" here) is inserted properly to all the generated links but nothing has changed.

*default_corparch* - Here I have found that in case there are no "keywords" (aka "tags" in other applications) defined, the "all corpora" widget (available when you click the button with corpus name on it) is empty. To make it work, at least one "keyword" must be attached to each defined corpus. But even in such case, once I start to write a part of a corpus name, an expected result is returned.

Example of my *corplist.xml*:

```xml
<kontext>
  <corplist>
    <keywords>
      <keyword ident="intercorp">
        <label lang="en">InterCorp</label>
        <label lang="cs">InterCorp</label>
      </keyword>
      <keyword ident="diachronic">
        <label lang="en">diachronic</label>
        <label lang="cs">diachronní</label>
      </keyword>
      <keyword ident="written">
        <label lang="en">written</label>
        <label lang="cs">psaný</label>
      </keyword>
      <keyword ident="parallel">
        <label lang="en">parallel</label>
        <label lang="cs">paralelní</label>
      </keyword>
    </keywords>
    <corpus ident="SUSANNE">
      <metadata>
        <keywords><item>written</item></keywords>
      </metadata>
    <corpus ident="intercorp_cs">
      <metadata>
        <keywords><item>written</item><item>parallel</item></keywords>
      </metadata>
    </corpus>
    <corpus ident="intercorp_en">
      <metadata>
        <keywords><item>written</item><item>parallel</item></keywords>
      </metadata>
    </corpus>
  </corplist>
  <corpus sentence_struct="s" ident="DIAKORP_V6" tagset="pp_tagset" collator_locale="cs_CZ">
    <metadata>
      <keywords><item>diachronic</item><item>written</item></keywords>
    </metadata>
  </corpus>
</kontext>
```

**Comment by tomachalek** [comment]
Talking about *default\_corparch*, you can try to find out which corpora from you xml config list are filtered out and also whether the corpora identifiers are ok (file *lib/plugins/default\_corparch/\_\_init\_\_.py*):

```python
    def get_list(self, plugin_api, user_allowed_corpora):
        """
        arguments:
        user_allowed_corpora -- a dict (corpus_canonical_id, corpus_id) containing corpora ids
                                accessible by the current user
        """
        simple_names = set(user_allowed_corpora.keys())
        cl = []
        import logging  # << added import
        for item in self._raw_list(plugin_api.user_lang).values():
            canonical_id, path, web = item['id'], item['path'], item['sentence_struct']
            # added logging >> 
            logging.getLogger(__name__).info(
                'Testing corp %s, in permitted?: %s' % (canonical_id, canonical_id in simple_names))
            if canonical_id in simple_names:
        # etc....
```

**Comment by lylax47** [comment]
Thank you for getting back so quickly! I will try all this out later today.

**Comment by lylax47** [comment]
So I tried your suggestions and pulled the updates finally. Sorry about the wait:

Fixed:

1. login and function now uses the correct url specified in the config file.

2. Keywords are functioning normally.

3. Searching through the widget also works as expected. (name or keywords, however only for susanne)

Issues:

1.  Logout uses the correct url, but the logout function no longer works. It return an error "unknown action[logout]"

2. Treearch does not function at all. It does not display any corpora.

3. Default corparch does appear to work, but not for our corpus. I tested this by creating a dummy corpora from Susanne and default was able to display both of them without a problem. The problem then likely seems to be with the corpus itself or with our registry file. I've attached the registry file for convenience. Any ideas on why the corpus would function if found manually with the url, but not appear in corparch?

4. The favoriting button does not appear to function (the start). For the time being does this need to set manually?

As always I really really appreciate all of your help. I'll be back in Moscow on Sunday, so I'll try out any suggestions you have then!

**Comment by lylax47** [comment]
I can't attach it so here is the registry file below:

```
MAINTAINER  "your@yourdomain.com"
NAME	    "RNCmain"
INFO	    "RNCmain"
INFOHREF    "http://hsecompling.wikispaces.com/visual"
TAGSETDOC   "http://nl.ijs.si/ME/V4/msd/html/msd-ru.html"

LANGUAGE    "Russian"
ENCODING    "utf-8"
LOCALE	    "ru_RU.UTF-8"

PATH        "/var/www/kontext/corpora/corplist/RNCmain"
VERTICAL    "/var/www/kontext/corpora/corplist/RNCmain/vert/RNCmain.vert"

MAXCONTEXT  0
MAXDETAIL   0

# ----------------------------------------------------------- # attributes with lowercase & multivalues (28apr16)

ATTRIBUTE word {
    TYPE "FD_FGD"
}

ATTRIBUTE lemma {
    TYPE "FD_FGD"
    MULTIVALUE yes
    MULTISEP "|"
}

ATTRIBUTE tag {
    TYPE "FD_FGD"
    MULTIVALUE yes
    MULTISEP "|"
}

ATTRIBUTE lc {
    LABEL "word (lowercase)"
    DYNAMIC utf8lowercase
    DYNLIB internal
    ARG1 "C"
    FUNTYPE s
    FROMATTR word
    TYPE index
    TRANSQUERY yes
}

ATTRIBUTE lemma_lc {
    LABEL "lemma (lowercase)"
    DYNAMIC utf8lowercase
    DYNLIB internal
    ARG1 "C"
    FUNTYPE s
    FROMATTR lemma
    TYPE index
    TRANSQUERY yes
}

# ----------------------------------------------------------- # PoS tags mapping, MTE Russian tagset (03nov15)

#WPOSLIST ",Nn,N.*,Aj,A.*,Pn,P.*,Nm,M.*,Vb,V.*,Av,R.*,Pp,S.*,Cj,C.*,Ij,I.*,Pt,Q.*,Ab,Y.*,Xx,X.*"
                                                                                    
# ----------------------------------------------------------- # structures with dynamics (12jan16)

STRUCTURE doc {
    TYPE "map64"
    ATTRIBUTE docid {
    TYPE "UNIQUE"
    }
    ATTRIBUTE header
    ATTRIBUTE author
    ATTRIBUTE created
    ATTRIBUTE words
    ATTRIBUTE sex
    ATTRIBUTE sphere
    ATTRIBUTE genre_fi
    ATTRIBUTE type
    ATTRIBUTE style
    ATTRIBUTE audience_age
    ATTRIBUTE audience_level
    ATTRIBUTE audience_size
    ATTRIBUTE source
    ATTRIBUTE publication
    ATTRIBUTE publ_year
    ATTRIBUTE medium
    ATTRIBUTE subcorpus
    ATTRIBUTE chronotop
    ATTRIBUTE birthday
}



#STRUCTURE font {
#    ATTRIBUTE type
#}

#STRUCTURE p {
#    TYPE "map64"
#    ATTRIBUTE heading
#    ATTRIBUTE langdiff
#    ATTRIBUTE pid {
# 	TYPE "UNIQUE"
#    }
#    ATTRIBUTE neardupe
#    DISPLAYTAG 0
#    DISPLAYEND "¶"
#}

STRUCTURE s {
    TYPE "map64"
    ATTRIBUTE neardupe
    DISPLAYTAG 0
    DISPLAYEND "¶"
#   ATTRIBUTE sid {
#	TYPE "UNIQUE"
#   }
}

STRUCTURE g {
    TYPE "map64"
    DISPLAYTAG 0
    DISPLAYBEGIN "_EMPTY_"
}
```

**Comment by lylax47** [comment]
Good evening! I am beyond disappointed in myself right now. The problem was so simple. All I needed to do was change the file names and the Redis entry so to lowercase. I am so sorry if I wasted a lot of your time with this issue.

**Comment by lylax47** [comment]
Also out of curiosity, does favoriting through the GUI currently function in this build, or does it need to be set manually in the corparch list?

**Comment by tomachalek** [comment]
Hi @lylax47, no problem. The important thing is you have been able to resolve the issue.

As regards favoriting of corpora/subcorpora, there are two categories actually (I hope that I've understood your question well):
1) featured corpora  - these are set manually in corpora XML config and they apply for all the users (the XML can be seen in one of my previous posts here - it is just a *\<featured /\>* tag added under *\<metadata\>*)
2) favorite corpora - individual user's selection which should work out of the box (just by clicking the "star" icon or by removing items from small corpus selection widget on the query form page)

Feel free to create a new ticket in case you are unable to make this work.

**Comment by lylax47** [comment]
Yes you have, and i just checked the kontext logs. All I needed to do was add a <max_num_favorites> value under corparch. Setting featured corpora works as well.  I also figured out the problem with the logout not functioning. I needed to put the address as "http://localhost/kontext/user/logoutx" instead of "http://localhost/kontext/user/logout". Everything seems to be working now as needed!

**Comment by lylax47** [comment]
Hi Toma!

We created russian documentation for our deployment of Kontext, and I was wanted to add it to the list of possible help manuals under the help option on the main menu bar. How could I go about doing this?

**Comment by lylax47** [comment]
Thanks again! Here is currently where the our build is based (http://web-corpora.net/kontext). We've also added a short user manual  in Russian under the help button. We're also working on constructing a Russian language option for the page. I will send it to you when it gets finished, but it will likely not be until 2 months or so after some time frees up.

**Comment by tomachalek** [comment]
It is good news indeed! Once you have a Russian translation of the user interface or some documentation I will gladly add that to the project.

**Comment by lylax47** [comment]
Good morning!

We recently noticed that for one of our corpora there is a blank attribute, that seems to capture all attributes in that subsection ("sphere") as shown in the print screen below.  When you look at the individual documents after a search however, each document has a sphere attribute already.

![image](https://cloud.githubusercontent.com/assets/15244289/25312894/d326668a-282c-11e7-90b9-f0f6c6a06030.png)

Also, do you know why doc id's and text type's are greyed out here, even after producing a query?

![image](https://cloud.githubusercontent.com/assets/15244289/25312905/1e0e7b24-282d-11e7-9496-9c2b79b26f50.png)

**Comment by tomachalek** [comment]
Hello,
let's start with the second question as it is the easier one (at least for me).

## 2)
 *Doc IDs* should appear once you add *SHORTREF* configuration value to corpus' registry (aka configuration) file (please note the *equal* sign):

```
SHORTREF "=doc.title"
```

The *Text Types* item should be available once you add *FREQTTATTRS*:

```
FREQTTATTRS "doc.txtype_group,doc.txtype,doc.genre_group"
```
Or you can define  *SUBCORPATTRS* which are primarily designated to be used for the "create subcorpus" page (= attributes user can use to specify his/her corpus) but in case you do not have *FREQTTATTRS* defined, KonText will use *SUBCORPATTRS* instead.

## 1)

I am not sure I understand this one well. You mean that by selecting the blank value in *doc.sphere* KonText will return documents with all the available values of *doc.sphere*?

**Comment by lylax47** [comment]
Good evening! Sorry for not responding, I've been very sick the past few days. To answer your question yes, there is and extra attribute under doc.sphere which selects all documents and every value. I suppose it could be connected to the corpus somehow, but I have no idea what could be causing it.

**Comment by lylax47** [comment]
I was wondering about two more things I stumbled across today:

1.) When creating subcorpora, kontext always defaults to naming the subcorpora as the default corpus listed in the kontext config file. The corpus is created correctly using the correct corpus, but is names it incorrectly using the default corpus name. However when no default is listed, then creating subcorpora is impossible. Have you encountered this before?

2.) Also what is meant by "negative filters disabled for multi-level freqs"? Is it impossible to include negative filtration when looking at text types?
