### ISSUE TITLE
Location of corplist.xml

### ISSUE THREAD

**Issue by PeterGilles** [czcorpus/kontext#1937]
The build of konText seems to be OK, but I cannot access the corpora, 'Available corpora' remains empty (URL: http://<server>:5000/corpora/corplist). I assume there is a config problem with corplist. 
My corparch section in config.xml:

>            <corparch>
>             <module>default_corparch</module>
>             <js_module>defaultCorparch</js_module>
>             <file>/var/lib/corpora/registry/corplist.xml</file>
>             <root_elm_path>//corpora/corplist</root_elm_path>
>             <tag_prefix extension-by="default">+</tag_prefix>
>             <max_num_hints extension-by="default">10</max_num_hints>
>             <default_page_list_size extension-by="default">30</default_page_list_size>
>             </corparch>

My corplist.xml:

> <?xml version="1.0"?>
>     <corplist>
>       <corpus ident="corpustest" sentence_struct="p" />
>   </corplist>

I have no obvious errors in the log file:

> 2017-10-03 16:48:35,400 [werkzeug] INFO:  * Running on http://<server>:5000/ (Press CTRL+C to quit)
> 2017-10-03 16:48:45,638 [werkzeug] INFO: 10.187.16.191 - - [03/Oct/2017 16:48:45] "GET / HTTP/1.1" 303 -
> 2017-10-03 16:48:45,976 [QUERY] INFO: {"user_id": 0, "proc_time": 0.0012, "settings": {"ctxattrs": "word", "shuffle": 1, "attr_vmode": "visible", "pagesize": 40, "wlpagesize": 25, "kwicrightctx": "10", "attrs": "word", "cup_hl": "q", "citemsperpage": 50, "kwicleftctx": "-10"}, "pid": 19217, "request": {"HTTP_USER_AGENT": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36", "REMOTE_ADDR": "10.187.16.191"}, "action": "nop", "params": {}, "user": "anonymous", "date": "2017-10-03 16:48:45.976270"}
> 2017-10-03 16:48:45,977 [werkzeug] INFO: 10.187.16.191 - - [03/Oct/2017 16:48:45] "GET /first_form HTTP/1.1" 303 -
> 2017-10-03 16:48:45,997 [QUERY] INFO: {"user_id": 0, "proc_time": 0.003, "settings": {"ctxattrs": "word", "shuffle": 1, "attr_vmode": "visible", "pagesize": 40, "wlpagesize": 25, "kwicrightctx": "10", "attrs": "word", "cup_hl": "q", "citemsperpage": 50, "kwicleftctx": "-10"}, "pid": 19217, "request": {"HTTP_USER_AGENT": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36", "REMOTE_ADDR": "10.187.16.191"}, "action": "corplist", "params": {}, "user": "anonymous", "date": "2017-10-03 16:48:45.997678"}
> 2017-10-03 16:48:46,051 [werkzeug] INFO: 10.187.16.191 - - [03/Oct/2017 16:48:46] "GET /corpora/corplist HTTP/1.1" 200 -

(The corpus corpustest is running smoothly in Bonito).
Any help is appreciated.
P

**Comment by tomachalek** [comment]
I can see two possible causes:

1) A mismatch between `<root_elm_path>//corpora/corplist</root_elm_path>` and actual location of `<corpus>` elements in *corplist.xml*. In case your *corplist.xml* root element is `<corplist>` (as your config snippet above may suggest) the xpath search `//corpora/corplist` won't work. In such case, use e.g. the following structure:

```xml
<kontext>
  <corplist>
   <corpus />
  </corplist>
</kontext>
```

and config entry `<root_elm_path>/corplist</root_elm_path>`.

------------------------

2) Missing corpora permissions when using *default_auth* plug-in. This thing is not well documented at the moment so I've just made a simple script *lib/plugins/default_auth/scripts/install.py* for an initial users+permissions import. Please see the sample file *lib/plugins/default_auth/scripts/users.sample.json* and make a copy using credentials of your choice (at least the "anonymous" user should be present). Then you can just run the script:
```
python install.py users.json
```
After that, KonText should be able to list an intersection of corpora defined in *corplist.xml* and permissions for a concrete user.

**Comment by PeterGilles** [comment]
Thanks! One step further. I can see the corpus under 'Available corpora', which I've indicated under <default corpora>. When selecting this corpus I am transferred to 'Search in the corpus', which is completely empty though. The log shows no errors. I can, however, generate the word list.

I can log in, but an error is produced when trying to log out:

> 2017-10-04 11:16:27,268 [werkzeug] INFO: 192.168.4.94 - - [04/Oct/2017 11:16:27] "GET /first_form HTTP/1.1" 200 -
> 2017-10-04 11:18:00,379 [controller] ERROR: Unknown action [logout]
> Traceback (most recent call last):
>   File "public/../lib/controller.py", line 808, in run
>     raise NotFoundException(_('Unknown action [%s]') % path[0])
> NotFoundException: Unknown action [logout]

**Comment by PeterGilles** [comment]
When selecting the available corpus, I am transferred to the 'Search in the corpus', which is completely empty though. 
What is possible though, to generate the wordlist and also access the KWIC from there.

**Comment by tomachalek** [comment]
### ad logout problem
Please make sure your configuration (config.xml) `kontext/plugins/auth/logout_url` contains a proper value. It should be `[app address]/user/logoutx` (e.g. http://localhost:5000/user/logoutx)

### ad broken "search" page
This looks like a problem with client-side application initialization (probably plug-in related). You can try to open a developer toolbar in your web browser (Command-Option-I in Safari, Ctrl-Shift-I Chrome etc.) and look at the console whether it dumps any errors. If so, then please paste the error traceback/info here and I will try to find out what is the cause.

**Comment by PeterGilles** [comment]
One error:

> firstForm.js?v=e467c5:44 TypeError: Cannot read property 'getWidgetView' of null
>     at firstForm.js?v=e467c5:44
>     at T (common.js?v=e467c5:4)
>     at S (common.js?v=e467c5:4)
>     at j (common.js?v=e467c5:4)
>     at MutationObserver.dt (common.js?v=e467c5:4)

**Comment by PeterGilles** [comment]
Error when clicking on the favorite 'star' in 'Available corpora':

> POST http://engelmann.uni.lu:5000/user/set_favorite_item 500 (Internal Server Error)
>   | (anonymous) | @ | common.js?v=e467c5:5
> -- | -- | -- | --
>   | k | @ | common.js?v=e467c5:4
>   | Y | @ | common.js?v=e467c5:4
>   | g | @ | common.js?v=e467c5:5
>   | a.ajax | @ | corplist.js?v=e467c5:17
>   | a.ajax | @ | corplist.js?v=e467c5:17
>   | (anonymous) | @ | corplist.js?v=e467c5:19
>   | b.changeFavStatus | @ | corplist.js?v=e467c5:19
>   | (anonymous) | @ | corplist.js?v=e467c5:19
>   | b.$Dispatcher_invokeCallback | @ | common.js?v=e467c5:72
>   | b.dispatch | @ | common.js?v=e467c5:72
>   | d | @ | corplist.js?v=e467c5:20
>   | r | @ | common.js?v=e467c5:31
>   | a | @ | common.js?v=e467c5:29
>   | s | @ | common.js?v=e467c5:29
>   | f | @ | common.js?v=e467c5:29
>   | m | @ | common.js?v=e467c5:29
>   | r | @ | common.js?v=e467c5:32
>   | processEventQueue | @ | common.js?v=e467c5:29
>   | r | @ | common.js?v=e467c5:31
>   | handleTopLevel | @ | common.js?v=e467c5:31
>   | i | @ | common.js?v=e467c5:31
>   | perform | @ | common.js?v=e467c5:32
>   | batchedUpdates | @ | common.js?v=e467c5:31
>   | i | @ | common.js?v=e467c5:31
>   | dispatchEvent | @ | common.js?v=e467c5:31

When clicking on 'Details':

> Uncaught ReferenceError: layoutViews is not defined
>     at l.value (corplist.js?v=e467c5:20)
>     at l.value (corplist.js?v=e467c5:20)
>     at p._renderValidatedComponentWithoutOwnerOrContext (common.js?v=e467c5:30)
>     at p._renderValidatedComponent (common.js?v=e467c5:30)
>     at p._updateRenderedComponent (common.js?v=e467c5:30)
>     at p._performComponentUpdate (common.js?v=e467c5:30)
>     at p.updateComponent (common.js?v=e467c5:30)
>     at performUpdateIfNecessary (common.js?v=e467c5:30)
>     at Object.performUpdateIfNecessary (common.js?v=e467c5:31)
>     at s (common.js?v=e467c5:31)

**Comment by tomachalek** [comment]
### Ad broken "search" page (2)

The possible cause is the "taghelper" plug-in which is defined as *optional* but a related page initialization procedure fails to complete in case there is none set. I've merged a patch to the *master* branch which should solve this.

Other issue answers will follow after a break :)

**Comment by PeterGilles** [comment]
Unfortunately, the error remains after this update.

**Comment by tomachalek** [comment]
### Ad corpus detail 

I've fixed the error in master branch - it should work by now

### Ad setting a favorite corpus

This looks like a server error. Can you please try the action and paste here a respective record from your server log?

### other/general

Maybe I can try your config.xml (minus any sensitive data in case there are any) in my development environment to find out what's wrong. You can send me the config by e-mail if you want. My address is tomas.machalek (at) ff.cuni.cz

**Comment by PeterGilles** [comment]
### Ad favorite
Here is the log:

> 2017-10-04 16:47:59,997 [werkzeug] INFO: 192.168.4.94 - - [04/Oct/2017 16:47:59] "POST /user/set_favorite_item HTTP/1.1" 500 -
> 2017-10-04 16:48:01,194 [controller] ERROR: Traceback (most recent call last):
>   File "public/../lib/controller.py", line 916, in process_action
>     method_ans = method(self._request)
>   File "public/../lib/plugins/default_user_items/__init__.py", line 74, in set_favorite_item
>     uit.add_user_item(ctrl._plugin_api, item)
>   File "public/../lib/plugins/default_user_items/__init__.py", line 124, in add_user_item
>     if len(self.get_user_items(plugin_api)) >= self.max_num_favorites:
>   File "public/../lib/plugins/default_user_items/__init__.py", line 103, in max_num_favorites
>     return int(self._settings.get('plugins', 'corparch')['default:max_num_favorites'])
> KeyError: 'default:max_num_favorites'

**Comment by tomachalek** [comment]
### Ad setting a favorite corpus (2)
Please add `<max_num_favorites extension-by="default">15</max_num_favorites>` (possibly with a different number) to your `kontext/plugins/corparch` settings section.  I am going to fix *config.sample.xml* which does not contain the item.

### other

I have tried your config with paths to corpora indices changed to suit my environment and no error appeared. I will try to investigate the issue further tomorrow. At the moment, I can only recommend to update to the latest revision in master, compile project using `grunt production`, restart the webserver and reload the page without cache (Cmd-Shift-r on Safari, Ctrl F5 Chrome; or you can change your deployment_id in config.xml which should force cache flush).

**Comment by PeterGilles** [comment]
Thank you, Tomas. I can save the favorites now.

The other problems remain, though. I am running konText via python public/app.py for the moment, not on a webserver. Maybe that is also an issue? Selecting a function form the menu, e.g. collocations, will bock the page and it seems the system is stuck in loading something. There is no cpu activity though and nothing in the log file.

**Comment by tomachalek** [comment]
It must be something else. I've just tried the embedded server version and it seems to be running fine. I will try to come up with something (I was unable to make time for the issue today, but hopefully tomorrow will be better).

**Comment by PeterGilles** [comment]
I just ran an update and it seems to be better now: I have access to the menu items now and sorting is working. Thank you. But:

- I cannot create subcorpora: 
```
subcorpForm.js?v=ae988a:17 TypeError: Cannot read property 'getViews' of null
    at subcorpForm.js?v=ae988a:30
    at T (common.js?v=ae988a:4)
    at S (common.js?v=ae988a:4)
    at j (common.js?v=ae988a:4)
    at MutationObserver.dt (common.js?v=ae988a:4)
```
- Frequency > Node forms > stuck
- When not logged in, I am getting the pop-up to sign-in, but I cannot click on 'Sign-in'.
- As for collocations, I now get the pop-up window with the option, but when selecting 'Making a candidate list' the server gets stuck and I have to restart app.py.

**Comment by PeterGilles** [comment]
1. `<calc_backend conf="conf/celeryconfig.py">celery</calc_backend>` I couldn't find a 'multiprocessing' option.
2. 'Lemma' is grey, probably because I am not using a lemmatized corpus yet, 'custom' is not working.
3. I left celery config with the proposed sample. I cannot find a log file for celery. I am running standalone app.py. I thus didn't do the configuration mentioned for a dedicated server. Maybe that is the issue here.
